import type React from "react"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { AuthProvider } from "@/components/auth-provider" // Import AuthProvider
import { Toaster } from "@/components/ui/toaster" // Import Toaster
import { RealtimeWrapper } from "@/components/realtime-wrapper"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Local Printer App",
  description: "Generated by create next app",
    generator: 'v0.app'
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {children}
          <RealtimeWrapper />
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  )
}
